### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by Wemago** [andrew-worsfold/tailor#2]
How can I use Tailor to add custom post types?
Would love to list them in grid, carousel or slideshows just like we can do with posts.
Are you thinking in adding it?

**Comment by andrew-worsfold** [comment]
I've created a new [Portfolio](https://github.com/andrew-worsfold/tailor-portfolio) extension, which introduces a Project custom post type.  Following that example, it would be easy to create a new element to present any custom post type you like.

Extending the Posts element to allow for custom post types is possible, though will require some changes to things like the Meta setting (as category, tags etc. only apply to standard posts).  Given the existing in-built templating system, plugin/theme authors could then easily create their own custom template partials to change the frontend look and feel (see partials/content-project.php in the Portfolio extension).

**Comment by andrew-worsfold** [comment]
As custom posts are different in some significant way from standard posts (or should be at least), the best way to support custom posts is to create an extension like the Portfolio one mentioned above.  Extensions should be used for anything that's not going to be of use to most people.

I'll close this question, but if anyone would like to suggest a way to support custom posts that's universal, makes sense and is valuable, please let me know.

**Comment by Wemago** [comment]
Andrew why not setting in customize > element > posts > query options the post type option? You have there categories and tags. Would be useful and easy to add.

**Comment by andrew-worsfold** [comment]
Adding the option and applying that to the query is easy, you're right.  The hard bit is then knowing how to render the custom post type.

Standard posts have categories and tags and certain assumptions have been made around how they are presented (i.e., author name, date, category etc.).   Custom post types are, by definition, custom, would likely have different meta information and (presumably) and would need to be displayed differently (otherwise, what's the point in using them over standard posts?). 

If you can suggest a realistic way of getting around that problem, I will be happy to add a custom post type option.
