### ISSUE TITLE
Best way to customize css?

### ISSUE THREAD

**Issue by ManUtopiK** [andrew-worsfold/tailor#21]
Hi, I tested some page-builder plugins and I found Tailor very well structured. Awesome works!

I took a look on how to customizing css to follow my theme styleguide.
Perhaps best way is to override css in my theme, but I have the feeling that you've used a css framework to make tailor theme and certainly a pre-processor like gulp, grunt or postcss. So I would like to know if it's possible to override some file in the scss folders, and rebuild all css files.

Also, is there a documentation about css components used : grid, buttons, states... ?

**Comment by andrew-worsfold** [comment]
There are a couple of things happening with Tailor:

1. There are "frontend" styles, which include the default element styling, states and utility classes used by Tailor.  As a developer, you can choose to disable these and style the elements your own way (though you'd want to ensure you cater for the utility classes used which are few in number.

2. Custom CSS is applied to elements based on setting values.

Tailor has been designed to provide minimal styling so that theme and plugin developers can easily replace or extend the default styles to their liking.  Feel free to create your own frontend stylesheet to replace the default one provided (I'd take a look at the SCSS project and potentially even use some of those files in your custom project e.g., the "trumps"), or just extend the styles in your own stylesheet that loads afterwards and takes precedence.

Depending on the nature of your desired changes, you may also wish to change the CSS rules associated with default elements.  Check out the `generate_css` method of each element class to see what I'm referring to here.

The documentation is a work in progress, however I will be adding to it shortly.  Please don't hesitate to reach out again if you have any specific questions in the mean time though!
