### ISSUE TITLE
Entrance and hover animations

### ISSUE THREAD

**Issue by lunacroft** [andrew-worsfold/tailor#36]
It would be great if there're some entrance effects to all elements, like: slide in left, fade in, bounce, and so on. And we could select effect, duration and delay time. Here has a css project with all of it https://daneden.github.io/animate.css/

And maybe image hover effects too. Some examples: http://tympanus.net/Development/HoverEffectIdeas/index.html

**Comment by andrew-worsfold** [comment]
I agree that animation/transition effects will be useful for some people.

I've been playing around with a plugin/extension that does exactly this.  The reason I see this as an extension rather than a core feature is that it's unclear whether most people would make use of this type of feature; for those that don't it's unnecessary bloat.

I will keep chipping away at an extension (similar to the existing Portfolio and WooCommerce ones).  In the meantime, plugin and theme authors should have no trouble adding this type of functionality using the existing element/setting APIs.  If anyone has any working code that they'd like to submit for inclusion in an "animation" extension, please get in touch.

**Comment by lunacroft** [comment]
Great! I also think that lightness is an important point, and extensions preserve it. 
Thanks @andrew-worsfold

**Comment by BinaryMoon** [comment]
plus one for keeping this as an extra plugin for those who want it! :)

**Comment by andrew-worsfold** [comment]
@lunacroft -

The [Advanced Features extension](https://github.com/andrew-worsfold/tailor-advanced) includes entrance and hover animations, in addition to a number of other things.  You can also control the duration and delay of the entrance animations.

To try it, download both the extension and the latest version of Tailor from here (1.7.5).  I'll be adding both to the WordPress repo soon.

**Comment by lunacroft** [comment]
I'll try it! Thanks @andrew-worsfold! =)

**Comment by andrew-worsfold** [comment]
As this functionality is now present in the Advanced Features extension, I'll close this issue.
