### ISSUE TITLE
Different column widths for different screen sizes

### ISSUE THREAD

**Issue by MWDelaney** [andrew-worsfold/tailor#47]
Hello,
I often find myself needing to adjust column widths for the various responsive screen sizes I'm developing for. A quick-and-dirty example using Bootstrap classes might be as follows:

```
<section class="row">
    <article class="col-xs-12 col-sm-6 col-lg-8">
        Content goes here
    </article>
    <figure class="col-xs-12 col-sm-6 col-lg-4">
        <img src="image.png" class="img-responsive">
    </figure>
</section>
```

With Tailor I can only set the column widths once, and can't change them depending on the screen size. Am I missing something?

**Comment by andrew-worsfold** [comment]
@MWDelaney -

Specifying mobile and tablet specific column widths like in Bootstrap is not currently possible.  Bootstrap isn't used in the project, however I am interested in supporting something like this so long as it can be achieved without adversely affecting people who have no use for this level of control.

What you can do in Tailor at the moment:
1. Specify custom classes for both rows and columns.
2. Select the breakpoint at which columns collapse into a single column.

One factor to overcome is that columns in Tailor are added and resized using drag and drop.  I'm putting together a free advanced extension for more advanced features that not everyone will be interested in to avoid "feature bloat" in the core plugin.  Perhaps a couple of settings could be added through that to control the individual column widths on various screen sizes.

Interested to get your thoughts on what this could realistically look like in the context of Tailor.

**Comment by MWDelaney** [comment]
Is it possible for the Tailor canvas to know which device preview "mode" you're currently in? Could the drag-to-resize columns (and classes) be set and saved per "device mode"?

That way you could set your column widths for desktop (a typical default view when working in Tailor) and then switch the view mode to tablet, resize the columns, and both settings would be saved. This way editing is always done in context with the device you're styling for, and doesn't add clutter to the settings screens. 

The output would necessarily be something like Bootstrap's `sm-6 md-8` classes but it would get the job done.

**Comment by andrew-worsfold** [comment]
I like the idea, although suspect that it may suffer from some problems (e.g., dragging to resize collapsed columns).  Responsive settings of this sort are planned to be part of an upcoming free extension, so I will put some thought into how this could/should work.

Really keen to get feedback from you (and anyone reading this)!

**Comment by andrew-worsfold** [comment]
@MWDelaney -

Tailor 1.7.4 introduces both [nested](https://medium.com/@tailorwp/columns-on-steroids-df5a5a957d89#.rpmprkm43) and [responsive](https://medium.com/@tailorwp/columns-are-now-more-responsive-1e2cf793b11f) columns.  Enjoy.

**Comment by reefki** [comment]
@andrew-worsfold Thanks for improve the column element that now uses percentage instead of 12 grid.

However I think it would be awesome if there is a field to manually enter the width because I have a little problem resizing the column using the mouse to get the exact width for example 1/3 column currently I get 33.4% which should be 33.3333333333%

I know it very tiny difference between 33.4% and 33.3333333333% but the displayed result quite make a big difference with 33.3333333333% I get 370px which is perfect pixel but with 33.4% I get only 369.45px, some of image inside becomes blurry because the column size is lower than 370px

Another benefit of adding column width field is ability to set different column widths on mobile and tablet. Now I take a sidebar as example I want to have a 1/3 (33.3333333333%) on desktop/tablet and I want to make it full width on mobile devices. Here is what I get currently:

Desktop
![screen shot 2016-12-04 at 19 08 00](https://cloud.githubusercontent.com/assets/10998084/20866055/7a96bf0a-ba55-11e6-850c-bda378651285.png)

Tablet
![screen shot 2016-12-04 at 19 07 46](https://cloud.githubusercontent.com/assets/10998084/20866058/8862f798-ba55-11e6-986c-ff87979b30e5.png)

Mobile
![screen shot 2016-12-04 at 19 07 34](https://cloud.githubusercontent.com/assets/10998084/20866060/8fe33064-ba55-11e6-9218-e0c2cff51ca8.png)

Look at the mobile view, the content is narrowed than the sidebar that looks a bit weird though. I know there is a visibility options which can be used to hide it on phones but that's not the point.

I look forward to hear your though on it.
