### ISSUE TITLE
Nested section / row

### ISSUE THREAD

**Issue by daviedR** [andrew-worsfold/tailor#49]
Hi Andrew, is there a chance to put section element inside a section (nested section)?

**Comment by andrew-worsfold** [comment]
Hi @daviedR - 

This is not currently possible.  What would be the desired outcome of doing that?

**Comment by joshmarom** [comment]
> What would be the desired outcome of doing that?

It allows you to create more advanced layouts

<img width="822" alt="screen shot 2016-10-10 at 12 00 25 pm" src="https://cloud.githubusercontent.com/assets/2726148/19231168/2b7782fa-8ee1-11e6-8ab7-c4c2b9c39208.png">

**Comment by andrew-worsfold** [comment]
If this is essentially a request for nested columns, there isn't a need for an additional nested section.  Layouts like the one above are achievable already (using a combination of columns and the Grid element).  

A free extension is underway to provide more advanced functionality and this may be a good candidate for inclusion in that (if there's sufficient demand).  I'll leave this request open and am keen to get feedback from others on this matter.

**Comment by daviedR** [comment]
Yes, it's for advanced layout flow.

Grid element has limitation, we can't make 1 grid item larger than the others, while a section element can do it.

Also, it would be great if we can override columns gap for each section, rather than using the page global setting.

**Comment by andrew-worsfold** [comment]
Thanks for confirming, @daviedR.

This is a candidate for the free advanced extension that I mentioned.

Regarding column gaps: these (along with section width and element spacing) can be configured in three areas:

1. In the **Customizer** (used as a global default and overrides the default in the stylesheets).
2. On a given page in the **Settings panel** (used as a page default and overrides the Customizer default); and
3. On **individual elements**, where appropriate (the highest level of specificity).

To configure the column spacing for a given set of columns, select the underlying row (not section) and update the column spacing setting.  You can think of sections as top level elements used for grouping and styling elements; they can contain rows and columns but are otherwise independent.

**Comment by andrew-worsfold** [comment]
@daviedR -

Nested columns are now available.  Check out this brief write up for more information:

https://medium.com/@tailorwp/columns-on-steroids-df5a5a957d89

While you're at it, check out the new responsive columns:

https://medium.com/@tailorwp/columns-are-now-more-responsive-1e2cf793b11f

**Comment by daviedR** [comment]
Looks awesome! Thanks @andrew-worsfold
