### ISSUE TITLE
Can't set padding on grid items

### ISSUE THREAD

**Issue by Arood** [andrew-worsfold/tailor#64]
When I had a look it seemed like the grid item only parse `"X-X-X-X"` instead of `"X,X,X,X" or "X-X-X-X"` like other elements do.

**Comment by andrew-worsfold** [comment]
Padding, margin and border width all use the same function for CSS rule generation now, but the problem here is that the specificity of the generated rule isn't high enough to override the default for Grid Items.

I've added a more specific selector in both the live preview JS and PHP code (i.e., `'&.tailor-grid__item'`).  This will be in the next release.

**Comment by andrew-worsfold** [comment]
@Arood - Can you please confirm whether the latest commit (1.7.3) resolves this issue for you?

**Comment by Arood** [comment]
Seems to work now! Thanks!
