### ISSUE TITLE
Save content data only in postmeta

### ISSUE THREAD

**Issue by 20y** [andrew-worsfold/tailor#9]
does it possible? as i can see you save data in postmeta in DB and on page / post content area in WP admin, why?

**Comment by andrew-worsfold** [comment]
I'm not sure what you mean when you say data is saved in the page/post content area.  Could you please clarify?

Are you referring to the shortcodes used for dynamic elements like Posts?  If so, this is to avoid having what is supposed to be a live section of content (e.g., your recent posts) become static HTML.

**Comment by 20y** [comment]
i mean that you save content in wp_postmeta in DB - http://take.ms/m99ax
and in post content in admin area - http://take.ms/Xq7B2
my question is: why you dont save content **ONLY** in wp_postmeta?

**Comment by andrew-worsfold** [comment]
I see what you're saying now. 

_tailor_saved_content is a sanitised copy of the HTML content generated by Tailor.  The reason it exists is to compare to the current post content: if it differs then we know that a page/post has been updated manually since it was saved in Tailor.

_tailor_original_content is a copy of the original page content before it was first Tailored.  The reason is exists is to provide a quick and easy way for users to revert to their "pre-Tailor" content, should they want to.

If you have ideas about how to handle tracking of manual changes to Tailored pages and reverting to original content, please let me know.  I know post revisions exist (and those can also be used to revert to the original content), but this is a convenience/shortcut for users.

**Comment by andrew-worsfold** [comment]
I have changed the way that metadata is used and these fields will no longer be used from version 1.4.0.

**Comment by andrew-worsfold** [comment]
The latest version of Tailor on GitHub (1.4.0) introduces a number of changes, including to the way that versions are managed.  This post meta is no longer used (only the element models are stored as post meta now).
